version: '3'

services:
  app1:
    build: ./app
    ports:
      - "3001:3000"
    environment:
      - MONGO_URL=mongodb://mongo1:27017
      - SERVER_NAME=app1
    depends_on:
      - mongo1
    networks:
      - stock-network
      
  app2:
    build: ./app
    ports:
      - "3002:3000"
    environment:
      - MONGO_URL=mongodb://mongo2:27018
      - SERVER_NAME=app2
    depends_on:
      - mongo2
    networks:
      - stock-network
    
  app3:
    build: ./app
    ports:
      - "3003:3000"
    environment:
      - MONGO_URL=mongodb://mongo3:27019
      - SERVER_NAME=app3
    depends_on:
      - mongo3
    networks:
      - stock-network

  mongo1:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017", "--quiet"]
    ports:
      - 27017:27017
    volumes:
      - mongo1_data:/data/db
      - mongo1_config:/data/configdb
    networks:
      - stock-network

  mongo2:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27018", "--quiet"]
    ports:
      - 27018:27018
    volumes:
      - mongo2_data:/data/db
      - mongo2_config:/data/configdb
    networks:
      - stock-network

  mongo3:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27019", "--quiet"]
    ports:
      - 27019:27019
    volumes:
      - mongo3_data:/data/db
      - mongo3_config:/data/configdb
    networks:
      - stock-network

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo1_config:
  mongo2_config:
  mongo3_config:

networks:
  stock-network:
    external: true
